"""
Zonentaxonomie: Alle bekannten OrKan-Zonencodes mit Standardwerten.
Dient als Wissensbasis für Stage 2 (Platzierungsalgorithmus).
"""

RACK_TYPES = [
    "Kragarmregal einseitig",
    "Kragarmregal zweiseitig",
    "Fachbodenregal",
    "Schubladenschrank",
    "Palettenregal",
    "Lagerkarton-Regal",
    "Hängeregal",
    "Bodenlagerfläche",
    "Sonstiges",
]

# priority: 1 = muss platziert werden, 2 = sollte, 3 = optional
ZONE_DEFAULTS: dict[str, dict] = {
    # 1_xx – Rohr
    "1_10": {
        "name": "Rohrlager",
        "category": "1_00 Rohr",
        "preferred_rack_types": ["Kragarmregal einseitig", "Kragarmregal zweiseitig"],
        "needs_wall": True,
        "typical_area_m2": 20.0,
        "min_depth_m": 1.2,
        "max_depth_m": 3.0,
        "needs_wall_length_m": 6.0,
        "adjacency_preference": ["1_11", "1_20"],
        "priority": 1,
        "notes": "Lange, freie Wandflächen für Kragarmregale benötigt. Möglichst nah an Warenannahme.",
    },
    "1_11": {
        "name": "Rohrrestelager",
        "category": "1_00 Rohr",
        "preferred_rack_types": ["Kragarmregal einseitig"],
        "needs_wall": True,
        "typical_area_m2": 8.0,
        "min_depth_m": 1.0,
        "max_depth_m": 2.0,
        "needs_wall_length_m": 3.0,
        "adjacency_preference": ["1_10"],
        "priority": 2,
        "notes": "Direkt neben Rohrlager.",
    },
    "1_20": {
        "name": "Rohrrollen",
        "category": "1_00 Rohr",
        "preferred_rack_types": ["Bodenlagerfläche"],
        "needs_wall": False,
        "typical_area_m2": 6.0,
        "min_depth_m": 1.5,
        "max_depth_m": 3.0,
        "needs_wall_length_m": 0.0,
        "adjacency_preference": ["1_10"],
        "priority": 2,
        "notes": "Bodenlagerung, rollbar.",
    },
    "1_30": {
        "name": "Retouren",
        "category": "1_00 Rohr",
        "preferred_rack_types": ["Fachbodenregal", "Bodenlagerfläche"],
        "needs_wall": False,
        "typical_area_m2": 4.0,
        "min_depth_m": 1.0,
        "max_depth_m": 2.5,
        "needs_wall_length_m": 0.0,
        "adjacency_preference": ["1_10"],
        "priority": 3,
        "notes": "",
    },
    # 2_xx – Befestigung
    "2_10": {
        "name": "Rohrschellen",
        "category": "2_00 Befestigung",
        "preferred_rack_types": ["Fachbodenregal", "Schubladenschrank"],
        "needs_wall": True,
        "typical_area_m2": 6.0,
        "min_depth_m": 0.6,
        "max_depth_m": 1.2,
        "needs_wall_length_m": 3.0,
        "adjacency_preference": ["2_20", "3_00"],
        "priority": 1,
        "notes": "",
    },
    "2_20": {
        "name": "Schrauben/Dübel",
        "category": "2_00 Befestigung",
        "preferred_rack_types": ["Schubladenschrank", "Fachbodenregal"],
        "needs_wall": True,
        "typical_area_m2": 6.0,
        "min_depth_m": 0.6,
        "max_depth_m": 1.0,
        "needs_wall_length_m": 2.0,
        "adjacency_preference": ["2_10"],
        "priority": 1,
        "notes": "",
    },
    # 3_00 – Fittings
    "3_00": {
        "name": "Fittings",
        "category": "3_00 Fittings",
        "preferred_rack_types": ["Fachbodenregal", "Lagerkarton-Regal"],
        "needs_wall": True,
        "typical_area_m2": 15.0,
        "min_depth_m": 0.6,
        "max_depth_m": 1.5,
        "needs_wall_length_m": 4.0,
        "adjacency_preference": ["2_10", "4_00"],
        "priority": 1,
        "notes": "",
    },
    # 4_xx – Installation / Heizung / Kundendienst
    "4_10": {
        "name": "Installationsmaterial",
        "category": "4_00 Installation",
        "preferred_rack_types": ["Fachbodenregal"],
        "needs_wall": True,
        "typical_area_m2": 12.0,
        "min_depth_m": 0.6,
        "max_depth_m": 1.5,
        "needs_wall_length_m": 4.0,
        "adjacency_preference": ["3_00", "4_20"],
        "priority": 1,
        "notes": "",
    },
    "4_20": {
        "name": "Heizungsmaterial",
        "category": "4_00 Installation",
        "preferred_rack_types": ["Fachbodenregal", "Palettenregal"],
        "needs_wall": True,
        "typical_area_m2": 15.0,
        "min_depth_m": 0.8,
        "max_depth_m": 2.0,
        "needs_wall_length_m": 4.0,
        "adjacency_preference": ["4_10", "4_30"],
        "priority": 1,
        "notes": "",
    },
    "4_30": {
        "name": "Armaturen",
        "category": "4_00 Installation",
        "preferred_rack_types": ["Fachbodenregal"],
        "needs_wall": True,
        "typical_area_m2": 8.0,
        "min_depth_m": 0.6,
        "max_depth_m": 1.2,
        "needs_wall_length_m": 3.0,
        "adjacency_preference": ["4_20"],
        "priority": 2,
        "notes": "",
    },
    # 20_00 – Abwasser
    "20_00": {
        "name": "Abwasser",
        "category": "20_00 Abwasser",
        "preferred_rack_types": ["Kragarmregal einseitig", "Fachbodenregal"],
        "needs_wall": True,
        "typical_area_m2": 12.0,
        "min_depth_m": 1.0,
        "max_depth_m": 2.5,
        "needs_wall_length_m": 4.0,
        "adjacency_preference": ["21_00"],
        "priority": 1,
        "notes": "Teilweise Großteile (Rohre/Schächte), Wandlagerung bevorzugt.",
    },
    # 21_00 – Sanitär
    "21_00": {
        "name": "Sanitär",
        "category": "21_00 Sanitär",
        "preferred_rack_types": ["Fachbodenregal"],
        "needs_wall": True,
        "typical_area_m2": 12.0,
        "min_depth_m": 0.6,
        "max_depth_m": 1.5,
        "needs_wall_length_m": 4.0,
        "adjacency_preference": ["20_00", "22_00"],
        "priority": 1,
        "notes": "",
    },
    # 22_00 – Kundendienst
    "22_00": {
        "name": "Kundendienst",
        "category": "22_00 Kundendienst",
        "preferred_rack_types": ["Fachbodenregal", "Schubladenschrank"],
        "needs_wall": True,
        "typical_area_m2": 10.0,
        "min_depth_m": 0.6,
        "max_depth_m": 1.2,
        "needs_wall_length_m": 3.0,
        "adjacency_preference": ["21_00"],
        "priority": 2,
        "notes": "Nah am Ausgang / Kundenbereich platzieren.",
    },
    # 30_00 – Rockwool / Dämmung
    "30_00": {
        "name": "Rockwool/Dämmung",
        "category": "30_00 Rockwool",
        "preferred_rack_types": ["Palettenregal", "Bodenlagerfläche"],
        "needs_wall": False,
        "typical_area_m2": 16.0,
        "min_depth_m": 1.5,
        "max_depth_m": 4.0,
        "needs_wall_length_m": 0.0,
        "adjacency_preference": [],
        "priority": 2,
        "notes": "Sperrgut, möglichst stapelbar. Zufahrt für Stapler berücksichtigen.",
    },
}

CATEGORY_COLORS = {
    "1_00 Rohr": "#3b82f6",
    "2_00 Befestigung": "#f59e0b",
    "3_00 Fittings": "#10b981",
    "4_00 Installation": "#8b5cf6",
    "20_00 Abwasser": "#06b6d4",
    "21_00 Sanitär": "#ec4899",
    "22_00 Kundendienst": "#f97316",
    "30_00 Rockwool": "#6b7280",
}

ZONE_CODE_OPTIONS = sorted(ZONE_DEFAULTS.keys())
CATEGORY_OPTIONS = sorted(set(v["category"] for v in ZONE_DEFAULTS.values()))
